CREATE DATABASE IF NOT EXISTS `launchtech`;
USE `launchtech`;


-- Table structure for table ebay customer

DROP TABLE IF EXISTS `e_customer`;
CREATE TABLE `e_customer`(
	id INTEGER NOT NULL auto_increment,
	ebay_id VARCHAR(50) UNIQUE NOT NULL,
	name VARCHAR(50) DEFAULT NULL,
	street VARCHAR(128) NOT NULL,
	city VARCHAR(50) NOT NULL,
	state VARCHAR(16) NOT NULL,
	postcode VARCHAR(10) NOT NULL,
	country VARCHAR(10) NOT NULL,
	mobile VARCHAR(20) DEFAULT NULL,
	phone VARCHAR(20)DEFAULT NULL,
	email VARCHAR(128)DEFAULT NULL,	
	create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
)ENGINE=InnoDB auto_increment=15 DEFAULT CHARSET=utf8;